# Generated by Django 5.2.4 on 2025-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
